apiVersion: v1
kind: Namespace
metadata:
  name: vector
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/marc0777/infra.git
    path: charts/vector
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vector
  syncPolicy:
    automated:
      selfHeal: true
