apiVersion: v2
name: victoria-metrics
version: 1.0.0
dependencies:
  - name: victoria-metrics-operator
    version: 0.58.1
    repository: https://victoriametrics.github.io/helm-charts
  - name: prometheus-operator-crds
    version: 27.0.0
    repository: https://prometheus-community.github.io/helm-charts
