---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-repo-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgAwwTgCSYSHWOP7ZuAoKHeoD3aD/6VTDhz2WZHqa1Foz9gHerheepU6Mv6S8/TrfhaFDQzCQifrGQmBJ5ht/uOfJRdOCSt/AYbCJRzI9u5icqn81y/8Zl+eD6VcborUCpM3pJZ25BGhFCAYtev/cWuLNel1hZdOhFveyghIKmICf0AqdAggNtY+yCB4QY5hBM62oB8hGeHyQg4j7D2ZcPS5JYRtDtWuouIyk7kf6X+SqOfFTBFnvLBgLbFj+jVQNZ6Eemynndg6cOrMDbEQLAq4oQrYbAnpsHf3z6DxYv76dZvmMvVptfMKWUVlP4dKhxUK/+lFZsshyINpShFVLADIENg9aUAxy7a/Co37CnU5lSXzn512tszlTcnqdbm3GGqV3ZtfsoSH5OuGStV1gBjFiI6kudX12W5JfEPJAY/OIXAXPCZbJTycaLTqxz1okeOcB4VcMiM64p5JmuKph+ja4s5S88SaiI1mvdPRb8espZU376sjB7YfIKxh18bD9LOmMufVj1pq39IdTY+HZC6thfiOYMb/9lnRGSJF2t6V59zLP1/HR4KqLBP6I0aeC/6jYdzqBuXRO2Yjep5+EZ7gLTSkeHzygvXMnTk4dsWpmaW92LM0F7XmK4FDGrkjOU+pRj9uC51WhMnxaZtEgcbPWVLUWdiLuu6hU2hoGgFpUvclT3+ADetOfzBdzIIDVkItL3/QdSGygeGr6/ppPei/o5Cbw//47XoceQ59LZvIcXUnpwKqbhF5t/ykq0DGCvhFdKkQo/xNNvNaE1S4Emp+mI40TRerkaAgbilZrOpAeJbglYkEhwjiGdVAi18=
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: homelab-repo-creds
      namespace: argocd
    type: Opaque
