---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pnogo-repo-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgBde44RzduPuks43CY0C6LgbMvD/wdQo4+rxFXIsInFweriFhbx1fqNxhzeJ/k46EyIkfea5RmqGtERdhe/7sOG1X+/20tnOoWTUHEKoNP1tkpIwjO31QkiTbh6fvVRJA7e2Ttoui2oUIaP/FZWvRP67hKzGpLpu/5h52VlZhGfei4liTYN6OfZsRjef7lkODU/6ngnlT1xqPWNU+Ae8y5NAPlHyAe+Q3GHHHWnfiPMlYDxu3jYW+8l/G1o5D5Cx95E60k7v5GmWBXBhhgxWWgHNodxRHQLYvpuR2HkhZ4A7U9X9V0nnVDli8ihfc0SXXs8UeK2j05aWCl1q0OsvTjHoEoKpetE3PmCuHSlmcsMcHsfVPVr22u1GJwORlqEHemjAnf/FolevDAyxQ73CJpibDNDlFwZzo8WGVyy4v4Me4qZ4/OtH9YwqyImbRw+FSokSAJ7fHYowtVhqBdhuw+b1YJsu6EpbLl/joYdEXn1QXkSl3payVXDuG6lLu3K4iu02GAb9zc7hcZhCakcaiQUgGXig9uEHvjREa362mg7DhoVDkaxWBjrprsDvgJ1hQAWiHQ7YGJpcSixoLdHIo8D5egEj7hlzEDYBNOTY3o9sjwBNV2YMCAzNhBC8zikV/ozCU9HhfNK6PZimJuwcUVOexwnFQCr+AjfP3g1EMADmuDH3k6nv3x6EnhQVioVkT6zEY70kEjOXfCAuTRORe8pDcUV1YGU4HqaDxLBRrCCF9rQDC/PJgwYwH4iq0/U51wSxH/sYyJxzG6va85Va96WWxrW254nSOxdSLgBXhUz4SEBw3mWqM6L9T8gp+Y=
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: pnogo-repo-creds
      namespace: argocd
    type: Opaque
